### ISSUE TITLE
Is it safe?

### ISSUE THREAD

**Issue by botted1** [Aetherinox/NETReflectorKeygen#1]
The exe is not detected in virustotal but I am still a little skeptical

**Comment by Aetherinox** [comment]
Sorry, no notifications on tickets.

Yes. You can download the exe for .NET Reflector straight from their website. 
And my keygen is nothing more than taking the algorithm utilized for serial generation and generating you a license key that the program thinks is legitimate. 

I make no calls to any outside websites, no tracking, no server nonsense. Keygen is nothing more than an interface with a few buttons.

**Comment by michaelviveiros** [comment]
> O exe não foi detectado no virustotal, mas ainda estou um pouco cético

en-US: I tested the latest version and it worked perfectly my friend @botted1 , as the @Aetherinox Aetherinox said, its code implements the same logic as the original algorithm, allowing us to activate Reflector correctly and it does not contain malicious code or any nature that comes from it.

pt-BR: Eu testei a última versão e funcionou perfeitamente amigo @botted1 , como o @Aetherinox Aetherinox disse, o código dele implementa a mesma lógica do algoritmo original nos possibilitando a ativação do Reflector de forma correta e o mesmo não possui código malicioso ou qualquer natureza que provenha disso.

**Comment by michaelviveiros** [comment]
> O exe não foi detectado no virustotal, mas ainda estou um pouco cético

en-US: I tested the latest version and it worked perfectly my friend @botted1 , as the @Aetherinox said, its code implements the same logic as the original algorithm, allowing us to activate Reflector correctly and it does not contain malicious code or any nature that comes from it.

pt-BR: Eu testei a última versão e funcionou perfeitamente amigo @botted1 , como o @Aetherinox disse, o código dele implementa a mesma lógica do algoritmo original nos possibilitando a ativação do Reflector de forma correta e o mesmo não possui código malicioso ou qualquer natureza que provenha disso.

**Comment by Aetherinox** [comment]
Thanks for this. I have merged your changes and updated the release.

**Comment by michaelviveiros** [comment]
> @michaelviveiros Thanks for this. I have merged your changes and updated the release. Going to close this since there's no reply from @botted1. Open a new issue if anything is spotted.

Thank you friend, count on me, success for you!
